# Generated by Django 4.1.7 on 2023-12-12 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('project_description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date of update')),
                ('end_date', models.DateTimeField(verbose_name='date of completion')),
                ('projectStatus', models.CharField(choices=[('To do', 'To Do'), ('In progress', 'In Progress'), ('Done', 'Done')], default='To do', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
