# Generated by Django 4.1.7 on 2023-12-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of completion'),
        ),
    ]
