# Generated by Django 4.1.7 on 2023-12-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_project_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectStatus',
            new_name='status',
        ),
    ]
