# Generated by Django 4.1.7 on 2023-12-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_projectstatus_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='projectStatus',
        ),
    ]
