# Generated by Django 4.1.7 on 2024-01-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_status_project_projectstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.AddField(
            model_name='project',
            name='projectPriority',
            field=models.CharField(choices=[('Crytical', 'Crytical'), ('High', 'High'), ('Normal', 'Normal'), ('Low', 'Low')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectStatus',
            field=models.CharField(choices=[('Locked', 'Locked'), ('To do', 'To Do'), ('In progress', 'In Progress'), ('Done', 'Done'), ('Duplicate', 'Duplicate'), ('New', 'New'), ('Impossible', 'Impossible')], default='To do', max_length=20),
        ),
    ]
