# Generated by Django 4.1.7 on 2024-01-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_project_end_date_project_projectpriority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='update_date',
        ),
        migrations.AddField(
            model_name='project',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
