# Generated by Django 4.1.7 on 2024-09-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_assigneduserchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedUserChange',
        ),
    ]
