# Generated by Django 4.1.7 on 2024-09-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_historicalproject_assigned_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProject_assigned_users',
        ),
    ]
